### ISSUE TITLE
Property is not resolved in an attribute

### ISSUE THREAD

**Issue by VoimiX** [seesharper/LightInject.Wcf#3]
I am trying to inject dependency via property in a custom attribute for wcf
But it always is null
```

 public class MyInspectorAttribute : Attribute, IOperationBehavior, IParameterInspector, IServiceBehavior
    {
        public IExternalService ExternalServiceInstance { get; set; } //always null

        public void AddBindingParameters(OperationDescription operationDescription, BindingParameterCollection bindingParameters)
        {
        }

        public void ApplyClientBehavior(OperationDescription operationDescription, ClientOperation clientOperation)
        {
        }

        public void ApplyDispatchBehavior(OperationDescription operationDescription, DispatchOperation dispatchOperation)
        {
           dispatchOperation.ParameterInspectors.Add(this); 



        }
}

```
I have attached simple solution which demonstrates this behaivor
https://drive.google.com/file/d/0B5-wpCN2u0zbcGRwSXdNdzNzblE/view?usp=sharing

Maybe there is another approach to solve my issue.

**Comment by seesharper** [comment]
Take a look at this 
http://stackoverflow.com/questions/28088393/injecting-a-dependency-into-an-attribute-using-unity-in-wcf

LightInject does not create the instance of your attribute so there is no way to populate the property. You could create a passive attribute that is just a marker. Register the IServiceBehavior with the container and it will be applied by LightInject.Wcf. If you want me to look into it in more detail, dump you sample app into a repo here on GitHub and I will PR into it.

**Comment by VoimiX** [comment]
Here is a repo with sample app


>Вторник, 15 ноября 2016, 12:27 +03:00 от Bernhard Richter <notifications@github.com>:
>
>Take a look at this 
>http://stackoverflow.com/questions/28088393/injecting-a-dependency-into-an-attribute-using-unity-in-wcf
>LightInject does not create the instance of your attribute so there is no way to populate the property. You could create a passive attribute that is just a marker. Register the IServiceBehavior with the container and it will be applied by LightInject.Wcf. If you want me to look into it in more detail, dump you sample app into a repo here on GitHub and I will PR into it. 
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Виталий Ситников

**Comment by VoimiX** [comment]
https://github.com/VoimiX/TestWcfAtrDependancy

**Comment by VoimiX** [comment]
https://github.com/VoimiX/TestWcfAtrDependancy  

> Вторник, 15 ноября 2016, 14:40 +03:00 от Виталий Ситников sitnikov.alpha@mail.ru:
> 
> Here is a repo with sample app
> 
> > Вторник, 15 ноября 2016, 12:27 +03:00 от Bernhard Richter < notifications@github.com >:
> > 
> > Take a look at this 
> > http://stackoverflow.com/questions/28088393/injecting-a-dependency-into-an-attribute-using-unity-in-wcf
> > LightInject does not create the instance of your attribute so there is no way to populate the property. You could create a passive attribute that is just a marker. Register the IServiceBehavior with the container and it will be applied by LightInject.Wcf. If you want me to look into it in more detail, dump you sample app into a repo here on GitHub and I will PR into it. 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly,  view it on GitHub , or  mute the thread .
> 
> ## 
> 
> Виталий Ситников

## 

Виталий Ситников

**Comment by seesharper** [comment]
https://github.com/VoimiX/TestWcfAtrDependancy/pull/1
