### ISSUE TITLE
precompiled publishing

### ISSUE THREAD

**Issue by isandburn** [seesharper/LightInject.Wcf#6]
hello - first off, great stuff with lightinject; keep up the good work.  

so this is not really an issue, as this is actually working as the .NET folks have intended/documented... but because of lightinject.wcf uses VirtualPathProvider, you will get lots of "endpoint not found"-ish errors if you precompile in an ASP.NET publish. 

i found out the hard way, did some digging, and found this: "If a Web site is precompiled for deployment, content provided by a VirtualPathProvider instance is not compiled, and no VirtualPathProvider instances are used by the precompiled site."  [here](https://msdn.microsoft.com/en-us/library/system.web.hosting.virtualpathprovider%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396).  i turned off precompilation and it was smooth sailing.  i love it when things just work :)

i just thought that perhaps you may be willing to drop a mention of this in your documentation to save the time and headache for others.

thanks!

**Comment by seesharper** [comment]
Updated docs. Thanks for your help 👍
